apiVersion: v1
kind: ConfigMap
metadata:
  name: js-vue-configmap
data:
  APP_NAME: "Laravel"
  APP_ENV: "local"
  APP_KEY: "base64:hrh9RJnhiMJB/qstCfoam2YFacHYbRozJhoilulb1pc"
  APP_DEBUG: "true"
  APP_URL: "http://localhost"

  LOG_CHANNEL: "stack"

  DB_CONNECTION: "mysql"
  DB_HOST: "jx-mysql"
  DB_PORT: "3306"
  DB_DATABASE: "js-vue-db"
  DB_USERNAME: "user"
  DB_PASSWORD: "user-pass"

  BROADCAST_DRIVER: "log"
  CACHE_DRIVER: "file"
  QUEUE_CONNECTION: "sync"
  SESSION_DRIVER: "file"
  SESSION_LIFETIME: "120"

  REDIS_HOST: "127.0.0.1"
  REDIS_PASSWORD: ""
  REDIS_PORT: "6379"

  MAIL_MAILER: "smtp"
  MAIL_HOST: "smtp.mailtrap.io"
  MAIL_PORT: "2525"
  MAIL_USERNAME: ""
  MAIL_PASSWORD: ""
  MAIL_ENCRYPTION: ""
  MAIL_FROM_ADDRESS: ""
  MAIL_FROM_NAME: "${APP_NAME}"

  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_DEFAULT_REGION: "us-east-1"
  AWS_BUCKET: ""

  PUSHER_APP_ID: ""
  PUSHER_APP_KEY: ""
  PUSHER_APP_SECRET: ""
  PUSHER_APP_CLUSTER: "mt1"

  MIX_PUSHER_APP_KEY: "${PUSHER_APP_KEY}"
  MIX_PUSHER_APP_CLUSTER: "${PUSHER_APP_CLUSTER}"

  JWT_SECRET: "n9wQBsGteiLTETucul0X7ilPtig74coL0C9NwYnnLywswMh1jE6XTnTorKaa8Dtd"
