# Default values for PHP.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: docker-registry.jx.k8s.trunksys.com/trunk-studio-interview/js-vue
  tag: 0.0.1
  pullPolicy: Always
service:
  name: js-vue
  type: NodePort
  externalPort: 80
  internalPort: 80
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"

resources:
  limits:
    cpu: "2"
    memory: 2Gi
  requests:
    cpu: "1"
    memory: 1Gi
