# Default values for node projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: draft
  tag: dev
  pullPolicy: IfNotPresent
service:
  name: cargocms-admin-client
  type: ClusterIP
  externalPort: 80
  internalPort: 4000
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
apiServiceName: cargocms-admin-client
resources:
  limits:
    cpu: 2000m
    memory: 1024Mi
  requests:
    cpu: 400m
    memory: 256Mi
probePath: /
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 10
readinessProbe:
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 10
terminationGracePeriodSeconds: 10
